# =============================================================================
# GitHub Container Registry Pull Secret
# =============================================================================
# Syncs dockerconfigjson from AWS Secrets Manager for pulling private images
# from ghcr.io. Run hydrate.sh to create the secret in AWS first.
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: xperts
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig }}"
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: dev/ghcr-pull-secret
---
# =============================================================================
# htpasswd Secret for HTTP Basic Auth
# =============================================================================
# Syncs htpasswd from AWS Secrets Manager for protecting ai and secops apps.
# Run hydrate.sh to create the secret in AWS first.
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xperts-htpasswd
  namespace: xperts
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: xperts-htpasswd
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: dev/xperts-htpasswd
        property: htpasswd
