# =============================================================================
# FortiWeb Credentials - External Secret
# =============================================================================
# Syncs FortiWeb API credentials from AWS Secrets Manager to Kubernetes.
# Used by the FortiWeb Ingress Controller to authenticate to FortiWeb API.
#
# Uses 'admin' user for full VIP creation permissions. The password is
# bootstrapped automatically by the fortiweb-bootstrap job, which changes
# the default password (instance-id) to the value in Secrets Manager.
#
# This secret is created by hydrate.sh:
#   Secret: dev/fortiweb
#   Username: admin (default)
#   Password: (user-provided during hydrate.sh)
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fortiweb-credentials
  namespace: fortiweb-controller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: fortiweb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dev/fortiweb
        property: username
    - secretKey: password
      remoteRef:
        key: dev/fortiweb
        property: password
